CREATE USER 'veea'@'localhost' IDENTIFIED BY 'aeev';
GRANT ALL PRIVILEGES ON veea.* TO 'veea'@'localhost';

CREATE DATABASE IF NOT EXISTS veea
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
USE veea;

CREATE TABLE IF NOT EXISTS user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(10) NOT NULL UNIQUE,
  full_name VARCHAR(80) NOT NULL,
  password_hash VARCHAR(80) NOT NULL,
  is_admin TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS session (
  user_id INT PRIMARY KEY,
  session_id VARCHAR(160) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_active TINYINT NOT NULL DEFAULT 1,
  FOREIGN KEY (user_id) REFERENCES user (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS video (
  video_id VARCHAR(20) PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS video_view (
  user_id INT,
  video_id VARCHAR(20),
  view_id VARCHAR(80) UNIQUE,
  view_duration FLOAT NOT NULL DEFAULT -1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (video_id) REFERENCES video (video_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (user_id) REFERENCES user (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  PRIMARY KEY (video_id, view_id)
);

CREATE TABLE IF NOT EXISTS video_view_time (
  id INT PRIMARY KEY AUTO_INCREMENT,
  view_id VARCHAR(80) NOT NULL,
  time FLOAT NOT NULL,
  state TINYINT NOT NULL,
  quality VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (view_id) REFERENCES video_view (view_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS video_view_stats (
  id INT PRIMARY KEY AUTO_INCREMENT,
  view_time_id INT NOT NULL,
  gender FLOAT NOT NULL,
  age INT NOT NULL,
  mood FLOAT NOT NULL,
  head_yaw FLOAT NOT NULL,
  head_pitch FLOAT NOT NULL,
  head_roll FLOAT NOT NULL,
  head_x FLOAT NOT NULL,
  head_y FLOAT NOT NULL,
  head_z FLOAT NOT NULL,
  head_gaze_x FLOAT NOT NULL,
  head_gaze_y FLOAT NOT NULL,
  happy FLOAT NOT NULL,
  surprised FLOAT NOT NULL,
  angry FLOAT NOT NULL,
  disgusted FLOAT NOT NULL,
  afraid FLOAT NOT NULL,
  sad FLOAT NOT NULL,
  engagement FLOAT NOT NULL DEFAULT 1,
  FOREIGN KEY (view_time_id) REFERENCES video_view_time (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
